# Generated by Django 3.2.9 on 2022-11-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='propertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('propertise_headline', models.CharField(max_length=300)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('total_bedroom', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('map_location', models.CharField(blank=True, max_length=300, null=True)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('squar_ft', models.CharField(blank=True, max_length=200, null=True)),
                ('preview1', models.ImageField(blank=True, null=True, upload_to='')),
                ('preview2', models.ImageField(blank=True, null=True, upload_to='')),
                ('preview3', models.ImageField(blank=True, null=True, upload_to='')),
                ('preview4', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
