# Generated by Django 3.2.9 on 2022-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221122_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertise',
            name='headline_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
